create table tb_associate (acd_id int8 generated by default as identity, acd_cpf varchar(255) not null, acd_name varchar(255), primary key (acd_id));
create table tb_schedule (sch_id int8 generated by default as identity, sch_description varchar(255), primary key (sch_id));
create table tb_session (ses_id int8 generated by default as identity, ses_duration int8 not null, ses_isopen boolean not null, ses_sch_id int8 not null, primary key (ses_id));
create table tb_votation (vot_id int8 generated by default as identity, vot_vote boolean not null, vot_acd_id int8 not null, vot_ses_id int8 not null, primary key (vot_id));
alter table if exists tb_session add constraint FK7p5w3k4s72i70brdurftbl44p foreign key (ses_sch_id) references tb_schedule;
alter table if exists tb_votation add constraint FKa8kf5w7xh93fpw3gtfa0n579b foreign key (vot_acd_id) references tb_associate;
alter table if exists tb_votation add constraint FKc590oanmgaboowx286hwuom9c foreign key (vot_ses_id) references tb_session;
